spring:
  data:
    mongodb:
      auto-index-creation: true

scheduler:
  priceParser:
    delay: 60000
  linkItemToStore:
    delay: 60000

webdriver:
  chrome:
    driver: "/usr/local/bin/chromedriver"
    logfile: "chromedriver.log"